Update 0-custom_http_response_header

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,37 +1,84 @@
 #!/usr/bin/env bash
-# Installs Nginx with the following configurations
-# Listen on port 80
-# return a page containing "Hello World!" with a curl GET request.
-# Configure an Nginx server to redirect /redirect_me to another page.
-# The redirection is configured as a 301 Moved Permanently.
-# Includes a custom 404 not found page with Ceci n'est pas une page".
+# duplicate web-01 to web-02
+# these scripts are an upgrade from the web-server scripts...
 
+# uncomment to see the script run in action
+#set -x
 
-apt-get update
-apt-get install -y nginx
+echo -e "Updating and doing some minor checks...\n"
 
-mkdir -p /var/nginx/html/
-touch /var/www/html/index.html
+function install() {
+	command -v "$1" &> /dev/null
+
+	#shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
+
+install nginx #install nginx
+
+echo -e "\nSetting up some minor stuff.\n"
+
+# allowing nginx on firewall
+sudo ufw allow 'Nginx HTTP'
+
+# Give the user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# create directories if not present
+for dir in /var/www/{html,error}; do
+	if ! [ -d "$dir" ]; then
+		mkdir -p "$dir"
+	fi
+done
+
+# creating new index
 echo "Hello World!" > /var/www/html/index.html
-touch /var/www/html/404.html
-echo "Ceci n'est pas une page" > /var/www/html/404.html
 
-printf %s "server {
-	listen 80 default_server;
-	listen [::]:80 default_server;
-	add_header X-Served-By $HOSTNAME;
-	root /var/www/html;
-	index index.html index.htm;
+# create new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
 
-	location /redirect_me {
-		return 301 http://cuberule.com/;
-	}
+# backup default server config file
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
 
-	error_page 404 /404.html;
-	location /404 {
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
 		root /var/www/html;
-		internal;
-	}
-}" > /etc/nginx/sites-available/default
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
 
-service nginx restart
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
